In [2]:
import numpy as np
import pandas as pd

from sqlalchemy import create_engine, select, text
engine = create_engine('postgresql://postgres:postgres@localhost:5432/skripsi')

import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, date
from  sklearn.impute import KNNImputer

In [5]:
data_existing = pd.read_csv('../preprocessed_main_data_dki1_kemayoran_v3_(preprocess_manual_for_app).csv', sep=',', decimal='.')
data_existing['tanggal'] = pd.to_datetime(data_existing['tanggal']).dt.date
data_existing.set_index('tanggal', inplace=True)

data_meteorologi_existing = data_existing[['Tavg', 'RH_avg', 'RR', 'ss', 'ff_avg', 'DDD_CAR']]

data_polutan_existing = data_existing[['pm10', 'pm25', 'so2', 'co', 'o3', 'no2']]

In [6]:
data_existing

,pm10,pm25,so2,co,o3,no2,Tavg,RH_avg,RR,ss,ff_avg,DDD_CAR,DDD_CAR_cos,DDD_CAR_sin
tanggal,,,,,,,,,,,,,,
2023-01-01,44.0,55.0,47.0,10.0,24.0,9.0,26.3,87.0,14.5,0.0,1.0,1.0,0.000000e+00,0.000000
2023-01-02,32.0,43.0,52.0,9.0,24.0,8.0,27.5,81.0,31.5,0.7,2.0,9.0,7.071068e-01,-0.707107
2023-01-03,31.0,35.0,49.0,9.0,12.0,7.0,26.6,82.0,0.5,0.0,1.0,1.0,0.000000e+00,0.000000
2023-01-04,30.0,47.0,53.0,11.0,15.0,9.0,26.4,86.0,2.4,2.1,1.0,1.0,0.000000e+00,0.000000
2023-01-05,38.0,50.0,50.0,13.0,26.0,11.0,27.4,83.0,35.3,4.9,2.0,1.0,0.000000e+00,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,53.0,83.0,12.0,10.0,11.0,36.0,29.2,78.0,7.5,1.2,2.0,1.0,0.000000e+00,0.000000
2024-12-28,64.0,101.0,14.0,9.0,11.0,35.0,30.0,70.0,0.6,3.8,2.0,1.0,0.000000e+00,0.000000
2024-12-29,51.0,21.0,13.0,10.0,13.0,35.0,29.7,73.0,0.0,3.0,1.0,1.0,0.000000e+00,0.000000
2024-12-30,35.0,10.0,13.0,5.0,12.0,13.0,28.4,76.0,1.0,1.8,2.0,7.0,-7.071068e-01,-0.707107
2024-12-31,29.0,11.0,6.0,13.0,10.0,18.0,28.4,76.0,2.0,2.4,2.0,8.0,-1.836970e-16,-1.000000

# Data meteorologi

In [9]:
data_for_app = pd.read_csv('./data meteorologi prepared/20250630 - 20250706.csv', sep=';')
data_for_app.rename(columns={'Tanggal': 'tanggal'}, inplace=True)
data_for_app

      tanggal  Tavg  RH_avg    RR   ss  ff_avg DDD_CAR
0  30-06-2025  28,1      79   2,1  0,4       1       C
1  01-07-2025  28,7      78  17,9    0       1       C
2  02-07-2025  28,2      78     0    0       1       C
3  03-07-2025  28,2      79    13    0       0       C
4  04-07-2025  28,7      74     0    0       0       C
5  05-07-2025  29,3      74     0  7,6       1       C
6  06-07-2025  26,7      83  35,2  6,6       1       C

In [10]:
data_for_app[['Tavg', 'RR', 'ss']] = data_for_app[['Tavg', 'RR', 'ss']].apply(lambda x: x.str.replace(',','.'))
data_for_app[['RR', 'ss']] = data_for_app[['RR', 'ss']].replace('-', np.nan)
data_for_app[['Tavg', 'RR', 'ss']] = data_for_app[['Tavg', 'RR', 'ss']].astype(float)

print(data_for_app['DDD_CAR'].unique())
data_for_app['DDD_CAR'] = data_for_app['DDD_CAR'].str.strip()
print("Kemayoran DDD_CAR stripped: ", data_for_app['DDD_CAR'].unique())

data_for_app['DDD_CAR'] = data_for_app['DDD_CAR'].replace({
  'C': 1,
  'N': 2,
  'NE': 3,
  'E': 4,
  'SE': 5,
  'S': 6,
  'SW': 7,
  'W': 8,
  'NW': 9
})
data_for_app['DDD_CAR'].unique()

data_for_app = data_for_app.replace([8888.0, 9999.0], np.nan)

data_for_app['tanggal'] = pd.to_datetime(data_for_app['tanggal'], format='%d-%m-%Y').dt.date
data_for_app.set_index('tanggal', inplace=True)

data_for_app_processed = data_for_app.copy()

['C']
Kemayoran DDD_CAR stripped:  ['C']

C:\Users\stevanus.febrian\AppData\Local\Temp\ipykernel_11424\490352085.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_for_app['DDD_CAR'] = data_for_app['DDD_CAR'].replace({

In [11]:
index_to_used = data_for_app.index
index_to_used

Index([2025-06-30, 2025-07-01, 2025-07-02, 2025-07-03, 2025-07-04, 2025-07-05,
       2025-07-06],
      dtype='object', name='tanggal')

In [12]:
data_meteorologi_concat = pd.concat([data_meteorologi_existing, data_for_app_processed])

In [13]:
# proses impute
# panggil data meteorologi
# lalu join indexnya dengan data_for_app_processed
# setelah diimpute, lalu ambil data yang tanggalnya ada di index_to_used

imputer = KNNImputer()
imputed_cuaca_kemayoran = pd.concat(
  [
    pd.DataFrame({'tanggal': data_meteorologi_concat.index}),
    pd.DataFrame(imputer.fit_transform(data_meteorologi_concat),columns = ['Tavg', 'RH_avg', 'RR', 'ss', 'ff_avg', 'DDD_CAR'])
  ], axis=1
)
imputed_cuaca_kemayoran[['Tavg', 'RR', 'ss']] = imputed_cuaca_kemayoran[['Tavg', 'RR', 'ss']].round(1)
imputed_cuaca_kemayoran[['RH_avg', 'DDD_CAR', 'ff_avg']] = imputed_cuaca_kemayoran[['RH_avg', 'DDD_CAR', 'ff_avg']].round(0)
imputed_cuaca_kemayoran.set_index('tanggal', inplace=True)

In [15]:
imputed_cuaca_kemayoran = imputed_cuaca_kemayoran[imputed_cuaca_kemayoran.index.isin(index_to_used)]
imputed_cuaca_kemayoran

            Tavg  RH_avg    RR   ss  ff_avg  DDD_CAR
tanggal
2025-06-30  28.1    79.0   2.1  0.4     1.0      1.0
2025-07-01  28.7    78.0  17.9  0.0     1.0      1.0
2025-07-02  28.2    78.0   0.0  0.0     1.0      1.0
2025-07-03  28.2    79.0  13.0  0.0     0.0      1.0
2025-07-04  28.7    74.0   0.0  0.0     0.0      1.0
2025-07-05  29.3    74.0   0.0  7.6     1.0      1.0
2025-07-06  26.7    83.0  35.2  6.6     1.0      1.0

In [9]:
# # impute linear interpolation
# # see surrounding dates
# startdate = pd.to_datetime('2023-10-21').date()
# enddate = pd.to_datetime('2023-10-25').date()
# imputed_cuaca_kemayoran.loc[startdate:enddate]

# # proses interpolate
# date_temp = pd.to_datetime('2023-10-23').date()
# columns_temp = ['Tavg', 'RH_avg', 'RR', 'ss', 'ff_avg', 'DDD_CAR']
# imputed_cuaca_kemayoran.loc[date_temp, columns_temp] = np.nan
# imputed_cuaca_kemayoran[columns_temp] = imputed_cuaca_kemayoran[columns_temp].interpolate(method ='linear', limit_direction ='forward')

In [16]:
#proses ubah representasi DDD_CAR
label_to_category = {
    1:'C', 2:'N', 3:'NE', 4:'E', 5:'SE', 6:'S', 7:'SW', 8:'W', 9:'NW'
}

category_to_degree = {
    'C': None, 'N':0, 'NE':45, 'E':90, 'SE':135, 'S':180, 'SW':225, 'W':270, 'NW':315  
}

cos_vals = []
sin_vals = []

imputed_cuaca_kemayoran['DDD_CAR_category'] = imputed_cuaca_kemayoran['DDD_CAR'].map(label_to_category)

for val in imputed_cuaca_kemayoran['DDD_CAR_category']:
    degree = category_to_degree.get(str(val), None)
    if degree is None: 
        cos_vals.append(0.0)
        sin_vals.append(0.0)
    else:
        rad = np.deg2rad(degree)
        cos_vals.append(np.cos(rad))
        sin_vals.append(np.sin(rad))

imputed_cuaca_kemayoran['DDD_CAR_cos'] = cos_vals
imputed_cuaca_kemayoran['DDD_CAR_sin'] = sin_vals
imputed_cuaca_kemayoran.pop('DDD_CAR')
imputed_cuaca_kemayoran.pop('DDD_CAR_category')
imputed_cuaca_kemayoran.head()

            Tavg  RH_avg    RR   ss  ff_avg  DDD_CAR_cos  DDD_CAR_sin
tanggal
2025-06-30  28.1    79.0   2.1  0.4     1.0          0.0          0.0
2025-07-01  28.7    78.0  17.9  0.0     1.0          0.0          0.0
2025-07-02  28.2    78.0   0.0  0.0     1.0          0.0          0.0
2025-07-03  28.2    79.0  13.0  0.0     0.0          0.0          0.0
2025-07-04  28.7    74.0   0.0  0.0     0.0          0.0          0.0

# data polutan

In [18]:
udara = pd.read_sql_query('select * from "daily_air_quality_dki1"',con=engine)
udara.head()

         time  so2  pm10  no2  co  o3  pm25
0  2025-06-01    0     0    0   0   0     0
1  2025-06-02   34    63   39  15  18   100
2  2025-06-03   30    57   45  16  16    85
3  2025-06-04   29    73   54  25  15   119
4  2025-06-05   30    73   51  23  17   116

In [22]:
# set 0 as nan
udara = udara[['time', 'pm10', 'pm25', 'so2', 'co', 'o3', 'no2']]
udara['time'] = pd.to_datetime(udara['time'], format='%Y-%m-%d').dt.date
udara.set_index('time', inplace=True)
udara = udara.replace(0, np.nan)

# next step join data meteorologi
udara_dan_meteorologi = udara.join(imputed_cuaca_kemayoran, how='inner')
udara_dan_meteorologi

KeyError: "['time'] not in index"

In [23]:
data_existing.columns

Index(['pm10', 'pm25', 'so2', 'co', 'o3', 'no2', 'Tavg', 'RH_avg', 'RR', 'ss',
       'ff_avg', 'DDD_CAR', 'DDD_CAR_cos', 'DDD_CAR_sin'],
      dtype='object')

In [24]:
udara_dan_meteorologi_dan_existing = pd.concat(
  [
    udara_dan_meteorologi, 
    data_existing[['pm10', 'pm25', 'so2', 'co', 'o3', 'no2', 'Tavg', 'RH_avg', 'RR', 'ss','ff_avg', 'DDD_CAR_cos', 'DDD_CAR_sin']]
  ]
)

In [25]:
imputed_udara = pd.concat(
  [
    pd.DataFrame({'tanggal': udara_dan_meteorologi_dan_existing.index}),
    pd.DataFrame(
      imputer.fit_transform(udara_dan_meteorologi_dan_existing),
      columns = ['pm10', 'pm25', 'so2', 'co', 'o3', 'no2', 'Tavg', 'RH_avg', 'RR', 'ss','ff_avg', 'DDD_CAR_cos', 'DDD_CAR_sin']
    )
  ], axis=1
)

In [27]:
imputed_data_for_app = imputed_udara.copy()
imputed_data_for_app.set_index('tanggal', inplace=True)
imputed_data_for_app = imputed_data_for_app[imputed_data_for_app.index.isin(index_to_used)]
imputed_data_for_app.to_csv('./data_for_app.csv', sep=',', decimal='.', index=True)